# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bde844e23a2c9e8be79de805e55edbb9f3d059fc0b9185c163657c1223be380c43c29c852704118c2d43c58dc3f14c2963eb5ae40cfa9d8699566d3ba85c662

test:
  secret_key_base: bb393b344989cc8ffc36ce66b37c775da630a4832a474e337390a679da1c646668c779996e855de3251d80b376c247321b3c62ce090ebcd89fc547df61751bed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
